spring:
  application:
    name: stock-service

server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#     defaultZone: http://localhost:8761/eureka/
#    eureka.client.service-url.default-zone: http://localhost:8083/eureka
    service-url:
     defaultZone: http://localhost:8083/eureka/



