spring:
  application:
    name: eureka-service

server:
  port: 8083

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    #eureka-server-connect-timeout-seconds: 5
    service-url:
        defaultZone: http://localhost:8083/eureka/

zuul:
  prefix: /api
  routes:
   stock-service:
        path: /stock-service/**
        url: http://localhost:8082
        #serviceId: stock-service
   db-service:
        path: /db-service/**
        url: http://localhost:8081
          #serviceId: db-service

